{{- if and .Values.node.enabled .Values.node.serviceAccount.create -}}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "kuack-node.serviceAccountName" . }}
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "kuack-node.labels" . | nindent 4 }}
  {{- with .Values.node.serviceAccount.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
{{- end }}
