{{- if and .Values.node.enabled .Values.node.cleanupOnUninstall.enabled }}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "kuack-node.fullname" . }}-uninstall-cleanup
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "kuack-node.labels" . | nindent 4 }}
  annotations:
    "helm.sh/hook": pre-delete
    "helm.sh/hook-weight": "-10"
    "helm.sh/hook-delete-policy": before-hook-creation,hook-succeeded
    checkov.io/skip1: CKV_K8S_41=Token automount required for kubectl commands in cleanup job
{{- end }}
